<?php

########################################################################
# Extension Manager/Repository config file for ext: "ws_login"
#
# Auto generated by Extension Builder 2012-04-27
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Websafari Social Login',
	'description' => 'Login extension for Twitter , Facebook and Google. Based on Extbase and Fluid.',
	'category' => 'plugin',
	'author' => 'Florian Rachor, Peter Grassberger, Augustin Malle, Miladin Bojic',
	'author_email' => 'f.rachor@websafari.eu, p.grassberger@websafari.eu, a.malle@websafari.eu, m.bojic@websafari.eu',
	'author_company' => 'websafari, websafari, websafari, websafari',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.4',
			'fluid' => '1.4',
			'typo3' => '4.6',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>